### PR TITLE
Returns false instead of throwing an error

### PR DESCRIPTION
**Pull request by rafet-ongun**
When guid is not supplied for a guid bucketed feature, returns false instead of throwing an error.

https://deliveroo.atlassian.net/browse/PROM-1156

### CODE REVIEW

**Review by adilh-d — APPROVED** [review]
LGTM as long as we get approval from the maintainers that the change of behaviour is acceptable

**Review by jphastings — CHANGES_REQUESTED** [review]
Please leave it so that this `ArgumentError` is still _raised_ internally, but caught in the `determinate` method ([remove these two lines](https://github.com/deliveroo/determinator/pull/111/files#diff-3b3a4056cae6c137dfb651ffd0aad4501131ed4b2b7feb16db68b4dde9f2e9b3L132-L133))

This will mean that Sentry will be notified when there is a badly configured experiment, otherwise it won't be clear there's anything wrong at all!

Also, you'll need to `git submodule update` once the other PR is complete, and also [bump the version used in the specs](https://github.com/deliveroo/determinator/blob/master/spec/determinator/control_spec.rb#L7) to `~1.2`.

(You'll also need to make the same changes to the Go, Scala and Javascript libraries too!)

**Comment by rafet-ongun** [comment]
@jphastings I've now made those changes. I've bumped the version from 1.1.3 to 1.1.5, because there was an update to 1.1.4 already [here](https://github.com/deliveroo/determinator-standard-tests/commit/cb568c8572667e4e93b473ac2cf5eee3e7a2dce6#diff-7b60b8e351cbb80c47459ffe2c79f1a26404871f49294780fe47ad0e58c09350).

**Review by me — APPROVED** [review]
Seems reasonable!

**Comment by me** [comment]
One question though: do we have a plan to update the Go and Scala libraries as well?

**Comment by rafet-ongun** [comment]
> One question though: do we have a plan to update the Go and Scala libraries as well?

Thanks @me , we've got [tickets](https://deliveroo.atlassian.net/jira/software/projects/PROM/boards/652/backlog?selectedIssue=PROM-1256) for them. But I cannot predict when they would be picked up.

**Comment by me** [comment]
> Thanks @me , we've got tickets for them. But I cannot predict when they would be picked up.

Thanks @rafet-ongun! Don't think it's super urgent - but we should get to it at some point, otherwise if people update the standard tests they will break.

**Review by jphastings — APPROVED** [review]

**Pull request merged**
